services:
  anubis_tea:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis_tea
    restart: unless-stopped
    environment:
      DIFFICULTY: "5"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://tea:3000"
      POLICY_FNAME: "/data/cfg/botPolicy.yml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tea.rule=Host(`git.rajimayur.me`)"
      - "traefik.http.routers.tea.entrypoints=websecure"
      - "traefik.http.routers.tea.tls=true"
      - "traefik.http.routers.tea.tls.certresolver=letsencrypt"
      - "traefik.http.services.tea.loadbalancer.server.port=8923"
      - "traefik.http.routers.tea.middlewares=headers-tea@docker"
      - "traefik.http.middlewares.headers-tea.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.headers-tea.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.headers-tea.headers.stsPreload=true"
      - "traefik.http.middlewares.headers-tea.headers.frameDeny=true"
      - "traefik.http.middlewares.headers-tea.headers.browserXssFilter=true"
      - "traefik.http.middlewares.headers-tea.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.headers-tea.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.headers-tea.headers.featurePolicy=accelerometer 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
      - "traefik.http.middlewares.headers-tea.headers.customResponseHeaders.Content-Security-Policy=default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self'; img-src 'self' data: https:; font-src 'self' data: https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests;"
    networks:
      - proxy_mother
    volumes:
      - "./botPolicy.yml:/data/cfg/botPolicy.yml:ro"
      - "./anubis-data:/data"
  tea:
    image: docker.gitea.com/gitea:latest-rootless
    container_name: tea
    labels:
      - app.maintainer = "libremaintainer@proton.me"
      - app.description = "Gitea server with a pg database"
      - app.version = "1.0"
    restart: always
    networks:
      - proxy_mother
    ports:
      - "2222:2222"
    depends_on:
      - tea_postgres_db
    env_file: .env
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=tea_postgres_db:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - ./gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./var/log/tea:/etc/lib/gitea/log

  tea_postgres_db:
    image: docker.io/library/postgres:18-alpine
    container_name: tea_postgres_db
    restart: always
    networks:
      - proxy_mother
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db-tea:/var/lib/postgresql

volumes:
  postgres-db-tea:
  gitea-config:

networks:
  proxy_mother:
    external: true
