use_default_settings: true
general:
  instance_name: "searXNG IN"
  mailto: libremaintainer@proton.me
  contact_url: "mailto:libremaintainer@proton.me"
  donation_url: "https://rajimayur.me/donate"

brand:
  custom:
    links:
      Uptime: "https://uptime.searxng.org/history/searx-rajimayur-me"
      About: "https://rajimayur.me"
  pwa_colors:
    background_color_dark: "#0f0010"
    theme_color_black: "#ff2bd6"
    background_color_black: "#0f0010"

search:
  safe_search: 2
  autocomplete: "google"
  autocomplete_min: 0
  favicon_resolver: "google"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineAccessDenied: 180
    SearxEngineCaptcha: 1800
    SearxEngineTooManyRequests: 180
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 604800

server:
  port: 8000
  bind_address: "0.0.0.0"
  base_url: "https://searx.rajimayur.me"
  limiter: true
  public_instance: true

  secret_key: "keyhere"
  image_proxy: true
  http_protocol_version: "1.0"
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

valkey:
  url: valkey://searxng-valkey:6379/0

ui:
  default_theme: simple
  theme_args:
    simple_style: "dark"
  search_on_category_select: true
  hotkeys: "vim"
  url_formatting: pretty

engines:
  - name: 360search
    engine: 360search
    disabled: true

  - name: ahmia
    inactive: true

  - name: torch
    inactive: true

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: bing images
    engine: bing_images
    shortcut: bii
    disabled: false
