services:
  proxy:
    image: traefik:latest
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - no-new-privileges:true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # named volume mount for traefik to store the certificates.
      - traefik-certs:/letsencrypt
      - "./var/:/var/log/traefik/"
      - "./dynamic:/dynamic:ro"
    command:
      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy_mother"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"

      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # API & Dashboard
      - "--api.dashboard=true"
      # Observability & logging
      - "--log.level=INFO"
      - "--log.filePath=/var/log/traefik/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filePath=/var/log/traefik/access.log"

        # Certificates
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=libremaintainer@proton.me"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

    # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing (Dashboard)
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.rajimayur.me`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.options=default"
      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$2a$10$4u6Gl8Yxjs2WyHEPGDeFBOottuPco54redvsb8wa80dWlOm.7qGpm"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker,headers-dashboard@docker"
      # Header Middleware
      - "traefik.http.middlewares.headers-dashboard.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.headers-dashboard.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.headers-dashboard.headers.stsPreload=true"
      - "traefik.http.middlewares.headers-dashboard.headers.frameDeny=true"
      - "traefik.http.middlewares.headers-dashboard.headers.browserXssFilter=true"
      - "traefik.http.middlewares.headers-dashboard.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.headers-dashboard.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.headers-dashboard.headers.featurePolicy=accelerometer 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
      - "traefik.http.middlewares.headers-dashboard.headers.customResponseHeaders.Content-Security-Policy=default-src 'self'; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests;"
    networks:
      - proxy_mother

volumes:
  traefik-certs:

networks:
  proxy_mother:
    external: true
