services:
  anubis_monitor:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis_monitor
    restart: unless-stopped
    environment:
      DIFFICULTY: "5"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://beszel:8090"
      POLICY_FNAME: "/data/cfg/botPolicy.yml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`mon.rajimayur.me`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls=true"
      - "traefik.http.routers.beszel.tls.certresolver=letsencrypt"
      - "traefik.http.routers.beszel.tls.options=default"
      - "traefik.http.services.beszel.loadbalancer.server.port=8923"
      - "traefik.http.routers.beszel.middlewares=headers-beszel@docker"
      - "traefik.http.middlewares.headers-beszel.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.headers-beszel.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.headers-beszel.headers.stsPreload=true"
      - "traefik.http.middlewares.headers-beszel.headers.frameDeny=true"
      - "traefik.http.middlewares.headers-beszel.headers.browserXssFilter=true"
      - "traefik.http.middlewares.headers-beszel.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.headers-beszel.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.headers-beszel.headers.featurePolicy=accelerometer 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
      - "traefik.http.middlewares.headers-beszel.headers.customResponseHeaders.Content-Security-Policy=default-src 'self'; script-src 'self' 'unsafe-inline' https:; style-src 'self'; img-src 'self' data: https:; font-src 'self' data: https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests;"
    networks:
      - proxy_mother
    volumes:
      - "./botPolicy.yml:/data/cfg/botPolicy.yml:ro"

  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://mon.rajimayur.me
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    networks:
      - proxy_mother

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    volumes:
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /proc:/proc:ro
      - /sys:/sys:ro
    environment:
      LISTEN: ${PORT}
      KEY: ${KEY}
      TOKEN: ${TOKEN}
      HUB_URL: http://beszel:8090
    networks:
      - proxy_mother

volumes:
  anubis-data:

networks:
  proxy_mother:
    external: true
