#!/usr/bin/bash

set -euo pipefail

printf "Bringing the instance down...\n"
docker compose down

printf "Pulling the latest and the greatest......\n"
docker compose pull

printf "Restarting (d to detach)...\n"
docker compose up -d

version=$(docker inspect searxng-core | grep image.version | cut -d: -f2 | sed 's/[," ]//g')

if [ "$?" -eq 0 ]; then
    echo -e "\e[1;32mSuccess.\e[0m"
    echo -e "\e[1;32mUpgraded to v$version\e[0m"
else
    echo -e "\e[1;31m***(Something failed during build)***\e[0m"
    exit 1
fi
